# Sets the log file name and path
logging.file.name=logs/app.log

# Custom pattern for file output
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Optional: Set specific log levels
logging.level.root=INFO

# Max size
logging.logback.rollingpolicy.max-file-size=10MB

